remote_theme: "y7kim/agency-jekyll-theme"
plugins:
  - jekyll-remote-theme

# Site settings
title: "Vivek Pandya"
email: "vivek.pandya501@gmail.com"
description: "Write an awesome description"

# Certifications, with pictures, name, and date
certifications:
  - name: "Microsoft Certified: Azure Fundamentals AZ 900"
    pic: azure
    date: "2023-06-10"
    validation_url: https://www.credly.com/badges/e73b9241-8ebe-4f62-a7ef-74f6abc961f1/linked_in_profile
  - name: "Microsoft Certified: Azure AI Fundamentals"
    pic: ai
    date: "2023-07-27"
    validation_url: https://www.credly.com/badges/e73b9241-8ebe-4f62-a7ef-74f6abc961f1/linked_in_profile
  - name: "Snowflake Warehousing Fundamentals"
    pic: snowflake
    date: "2023-09-27"
    validation_url: https://www.credly.com/badges/e73b9241-8ebe-4f62-a7ef-74f6abc961f1/linked_in_profile
  - name: "dbt Fundamentals"
    pic: dbt
    date: "2023-10-08"
    validation_url: https://www.credly.com/badges/e73b9241-8ebe-4f62-a7ef-74f6abc961f1/linked_in_profile
  - name: "Bloomberg Market Fundamentals"
    pic: bloomberg
    date: "2023-01-09"
    validation_url: https://www.credly.com/badges/e73b9241-8ebe-4f62-a7ef-74f6abc961f1/linked_in_profile
  - name: "Alteryx Designer Core Certified"
    pic: alteryx
    date: "2023-02-12"
    validation_url: https://www.credly.com/badges/e73b9241-8ebe-4f62-a7ef-74f6abc961f1/linked_in_profile

# Social networks usernames
social:
  - title: "twitter"
    url: "http://twitter.com/jekyllrb"
  - title: "github"
    url: "http://github.com/jekyll"

# Postal address (add as many lines as necessary)
address:
  - line: "3481 Melrose Place"
  - line: "Beverly Hills, CA 90210"

# Build settings
markdown: kramdown
permalink: pretty
